# Generated by Django 5.2.4 on 2025-10-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_is_featured_product_is_hot_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank if product is not on sale', max_digits=10, null=True),
        ),
    ]
