# Generated by Django 5.2.4 on 2025-10-01 19:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
