# Generated by Django 5.2.4 on 2025-10-01 19:55

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_full_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
    ]
